name: Publish module

on:
  workflow_dispatch:
    inputs:
      type:
        required: true
        default: 'create-canary'
        description: |
          Default will publish a canary build
          To publish a real build off main send 'publish-release'
      pr_number:
        required: false
        default: '0'
        description: 'PR to read from for canary build'

env:
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

permissions:
  contents: read # for checkout
  pull-requests: write  # for comments
  packages: write # for publish

jobs:
  start:
    name: Start publishing
    runs-on: ubuntu-latest
    if: startsWith(github.event.inputs.type, 'create-canary') && github.actor == 'maniator'
    steps:
      - run: gh pr comment -b "🎉 Canary Release build started" ${{github.event.inputs.pr_number}} -R ${{ github.repository }}
        
  npm:
    name: Publish to NPM
    runs-on: ubuntu-latest
    if: |
      (
        startsWith(github.event.inputs.type, 'create-canary') || 
        startsWith(github.event.inputs.type, 'publish-release') 
      ) && 
      github.actor == 'maniator'
    steps:
      - name: checkout
        uses: actions/checkout@v3
        
      - name: canary pr
        if: startsWith(github.event.inputs.type, 'create-canary')
        run: gh pr checkout ${{github.event.inputs.pr_number}} -R ${{ github.repository }}

      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ steps.nvm.outputs.NVMRC }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci

      - name: Authenticate with NPM Registry
        run: |
          echo "@serveside:registry=https://registry.npmjs.org/" > .npmrc
          echo "registry=https://registry.npmjs.org/" >> .npmrc
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish canary to npm
        if: startsWith(github.event.inputs.type, 'create-canary')
        run: npm run release:canary:ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Publish to GH
        if: startsWith(github.event.inputs.type, 'publish-release')
        run: npm run release:ci
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  gh:
    name: GH
    runs-on: ubuntu-latest
    if: |
      (
        startsWith(github.event.inputs.type, 'create-canary') || 
        startsWith(github.event.inputs.type, 'publish-release') 
      ) && 
      github.actor == 'maniator'
    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: canary pr
        if: startsWith(github.event.inputs.type, 'create-canary')
        run: gh pr checkout ${{github.event.inputs.pr_number}} -R ${{ github.repository }}
      
      - name: Read .nvmrc
        run: echo "##[set-output name=NVMRC;]$(cat .nvmrc)"
        id: nvm
      - name: Setup Node ${{ steps.nvm.outputs.NVMRC }}
        uses: actions/setup-node@v3
        with:
          node-version:  ${{ steps.nvm.outputs.NVMRC }}
          registry-url: 'https://npm.pkg.github.com'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      - name: Install
        run: npm ci

      - name: Authenticate with GH Registry
        run: |
          echo "@serveside:registry=https://npm.pkg.github.com/" > .npmrc
          echo "registry=https://npm.pkg.github.com/" >> .npmrc
          echo "//npm.pkg.github.com/:_authToken=$NPM_TOKEN" >> .npmrc
          npm whoami
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish canary to GH
        if: startsWith(github.event.inputs.type, 'create-canary')
        run: npm run release:canary:ci
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Publish to GH
        if: startsWith(github.event.inputs.type, 'publish-release')
        run: npm run release:ci
        env:
          NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-complete:
    name: Publishing Complete
    runs-on: ubuntu-latest
    needs:
      - start
      - gh
      - npm
    if: startsWith(github.event.inputs.type, 'create-canary') && github.actor == 'maniator'
    steps:
      - run: gh pr comment -b "🎉 Release complete" ${{github.event.inputs.pr_number}} -R ${{ github.repository }}
